resolver: lts-6.13
packages:
- '.'
- location:
    git:       git@github.com:JanGe/irc-client.git
    commit:    0957c8241937d13bd7c97fbdc6475ec9f1a75e97
  extra-dep: true
extra-deps:
- concurrent-extra-0.7.0.10
- irc-conduit-0.2.0.0
- irc-dcc-2.0.0
- safe-exceptions-0.1.4.0
